{
 "title": "NodeJS - HTTP",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "host.docker.internal:8081" }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP - Success requests (95 pt)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path) (http_request_duration_seconds_bucket{status=~\"(2|3)..\"})",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "HTTP - Size of Requests (95 pt)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path) (http_request_size_bytes_bucket{status=~\"(2|3)..\"})",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  },
  {
   "title": "HTTP - Size of Response (95 pt)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (method, path) (http_response_size_bytes_bucket{status=~\"(2|3)..\"})",
     "legendFormat": "{{method}} - {{path}}"
    }
   ]
  }
 ]
}